/*
 * This file is generated by jOOQ.
 */
package pl.klasicki.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import pl.klasicki.jooq.tables.Expense;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Budget extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>budget</code>
     */
    public static final Budget BUDGET = new Budget();

    /**
     * The table <code>budget.expense</code>.
     */
    public final Expense EXPENSE = Expense.EXPENSE;

    /**
     * No further instances allowed
     */
    private Budget() {
        super("budget", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Expense.EXPENSE
        );
    }
}
