/*
 * This file is generated by jOOQ.
 */
package pl.klasicki.jooq;


import pl.klasicki.jooq.tables.Expense;


/**
 * Convenience access to all tables in budget.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>budget.expense</code>.
     */
    public static final Expense EXPENSE = Expense.EXPENSE;
}
