spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/liquibase-changelog.yml
server:
  port: 8084
